name: Build Android APK (EAS)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Install and Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: ${{ hashFiles('yarn.lock') != '' && 'yarn' || 'npm' }}

      - name: Setup EAS CLI
        uses: expo/expo-github-action@main
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: |
          if [ -f "yarn.lock" ]; then
            yarn install --frozen-lockfile
          else
            npm ci --legacy-peer-deps
          fi

      - name: Inject Valid Project ID
        # Скрипт устанавливает утилиту jq, вырезает старый блок extra и вставляет гарантированно рабочий UUID
        run: |
          sudo apt-get install jq -y
          jq '.expo.extra.eas.projectId = "JKnev3gxHsBZ8tjXgcI5miJYDPZAdW0wrmRxeg9R"' app.json > temp.json && mv temp.json app.json
          echo "=== Проверка app.json ==="
          cat app.json | grep projectId

      - name: Build APK on Expo EAS
        run: eas build --platform android --profile preview --non-interactive
