name: Build Android APK (EAS)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Install and Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4 # Использование стабильного релиза v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24 # Явное указание Node.js 24 для соответствия стандартам GitHub
          cache: ${{ hashFiles('yarn.lock') != '' && 'yarn' || 'npm' }}

      - name: Setup EAS CLI
        uses: expo/expo-github-action@main
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: |
          if [ -f "yarn.lock" ]; then
            yarn install --frozen-lockfile
          else
            npm ci --legacy-peer-deps
          fi

      - name: Build APK on Expo EAS
        run: eas build --platform android --profile preview --non-interactive
