name: Build Android APK (EAS)

on:
  push:
    branches:
      - main # Скрипт сработает при пуше в ветку main (замените на master, если нужно)

jobs:
  build:
    name: Install and Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-size: 20
          cache: 'npm'

      - name: Setup EAS CLI
        uses: expo/openapi-action@v1
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install # или yarn install, если вы используете yarn

      - name: Build APK on Expo EAS
        run: eas build --platform android --profile preview --non-interactive
